apiVersion: v1
kind: Service
metadata:
  name: grpc-server
  namespace: grpc
spec:
  clusterIP: None #headless services
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: grpc-server