apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  namespace: grpc
  labels:
    name: API
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template:
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: nantaaditya/grpc-client:0.0.1
          imagePullPolicy: Never
          resources:
            requests:
              memory: 128Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 512m
          env:
            - name: GREETING_SERVICE_HOST
              value: "grpc-server.grpc:9090"
          ports:
            - containerPort: 8081