// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GreetingService.proto

// Protobuf Java Version: 3.25.3
package com.nantaaditya.grpc.proto;

public final class GreetingProto {
  private GreetingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nantaaditya_grpc_proto_HelloRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nantaaditya_grpc_proto_HelloRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_nantaaditya_grpc_proto_HelloReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_nantaaditya_grpc_proto_HelloReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025GreetingService.proto\022\032com.nantaaditya" +
      ".grpc.proto\"\034\n\014HelloRequest\022\014\n\004name\030\001 \001(" +
      "\t\"\035\n\nHelloReply\022\017\n\007message\030\001 \001(\t2q\n\017Gree" +
      "tingService\022^\n\010SayHello\022(.com.nantaadity" +
      "a.grpc.proto.HelloRequest\032&.com.nantaadi" +
      "tya.grpc.proto.HelloReply\"\000B-\n\032com.nanta" +
      "aditya.grpc.protoB\rGreetingProtoP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_nantaaditya_grpc_proto_HelloRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_nantaaditya_grpc_proto_HelloRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nantaaditya_grpc_proto_HelloRequest_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_com_nantaaditya_grpc_proto_HelloReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_nantaaditya_grpc_proto_HelloReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_nantaaditya_grpc_proto_HelloReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
