// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: GreetingService.proto

// Protobuf Java Version: 3.25.3
package com.nantaaditya.grpc.proto;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.nantaaditya.grpc.proto.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
